### ISSUE TITLE
"No valid keyboard connected!"

### ISSUE THREAD

**Issue by JarvisTheJelly** [Pixdigit/Project-Interstellar#23]
Not sure if this is intentional, but on every one of my laptops this message seems to come up.

Happen on startup.

**Comment by Pixdigit** [comment]
This is intentional if debugmode is true.
I use my digital piano (In german we call the really cheap ones "keyboard" therefore the name) for debug testing without having to worry with keys on the actual keyboard.
It might be a little overkill but since I use a really cheap midi to usb converter I want to be sure to know that the error is not in the midi bridge. A possible solution might be changing the print statement to when a "keyboard" is detected.

**Comment by JarvisTheJelly** [comment]
Oh a musical keyboard, that makes much more sense! I can see how that is a good thing to have.
